<?php
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
?><!doctype html>
<html lang="pt">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#111511"><title>Arcadia — Biblioteca de jogos</title>
  <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@400;500;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="assets/css/app.css"><script>window.APP_CONFIG = <?= json_encode(['csrf' => csrf_token()]) ?>;</script>
  <script src="assets/js/app.js" defer></script>
</head>
<body>
<div class="shell">
  <aside class="sidebar" id="sidebar">
    <a class="brand" href="#dashboard" aria-label="Arcadia, início"><span class="brand-mark">A</span><span>arcadia<span class="brand-dot">.</span></span></a>
    <div class="side-caption">MENU</div>
    <nav class="main-nav" aria-label="Navegação principal">
      <button class="nav-item active" data-page="dashboard"><span class="nav-icon">⌂</span>Visão geral</button>
      <button class="nav-item" data-page="library"><span class="nav-icon">▦</span>A minha biblioteca <span class="nav-count" id="nav-total">0</span></button>
      <button class="nav-item" data-page="wishlist"><span class="nav-icon">♡</span>Lista de desejos</button>
      <button class="nav-item" data-page="collections"><span class="nav-icon">▤</span>Coleções</button>
    </nav>
    <div class="sidebar-bottom"><div class="side-caption">A TUA COLEÇÃO</div><div class="library-progress"><div class="progress-top"><span>Jogos concluídos</span><b id="completion-label">0%</b></div><div class="progress-track"><span id="completion-bar"></span></div><small id="completion-count">0 de 0 jogos</small></div><div class="profile"><div class="avatar">J</div><div><strong>Jogador</strong><span>Biblioteca pessoal</span></div><span class="profile-menu">···</span></div></div>
  </aside>
  <main class="main-content">
    <header class="topbar"><button class="mobile-menu" id="mobile-menu" aria-label="Abrir menu">☰</button><div class="breadcrumb">A tua biblioteca <span>/</span> <b id="breadcrumb-current">Visão geral</b></div><div class="top-actions"><label class="global-search"><span>⌕</span><input id="global-search" type="search" placeholder="Pesquisar jogos…" aria-label="Pesquisar jogos"><kbd>⌘ K</kbd></label><button class="icon-button" id="theme-toggle" aria-label="Alternar tema" title="Alternar tema">◐</button><button class="button button-primary add-button" id="add-game"><span>＋</span> Adicionar jogo</button></div></header>
    <section class="page active" id="page-dashboard"><div class="welcome-row"><div><p class="eyebrow">A TUA JORNADA, AO TEU RITMO</p><h1>A tua próxima aventura<br><span>começa aqui.</span></h1><p class="subheading">Um espaço só teu para guardar, acompanhar e redescobrir jogos.</p></div><button class="button button-outline" data-go="library">Explorar biblioteca <span>↗</span></button></div>
      <div class="hero-card" id="featured"><div class="hero-no-game"><span class="hero-orb">✦</span><div><span class="eyebrow">O TEU DESTAQUE</span><h2>A tua história<br>começa com um jogo.</h2><p>Adiciona o primeiro título à tua biblioteca e começa a acompanhar o teu progresso.</p><button class="button button-primary" data-add>＋ Adicionar primeiro jogo</button></div></div></div>
      <div class="stats-grid"><article class="stat-card"><div class="stat-icon mint">▦</div><span>Total de jogos</span><strong id="stat-total">0</strong><small>Na tua coleção</small></article><article class="stat-card"><div class="stat-icon amber">◷</div><span>A jogar</span><strong id="stat-playing">0</strong><small>Prontos para continuar</small></article><article class="stat-card"><div class="stat-icon green">✓</div><span>Concluídos</span><strong id="stat-completed">0</strong><small>Aventura terminada</small></article><article class="stat-card"><div class="stat-icon rose">♡</div><span>Lista de desejos</span><strong id="stat-wishlist">0</strong><small>Para jogar a seguir</small></article></div>
      <div class="section-heading"><div><p class="eyebrow">A TUA COLEÇÃO</p><h2>Adicionados recentemente</h2></div><button class="text-button" data-go="library">Ver biblioteca <span>→</span></button></div><div class="game-grid recent-grid" id="recent-grid"></div>
      <div class="section-heading continue-heading"><div><p class="eyebrow">A AVENTURA CONTINUA</p><h2>A jogar agora</h2></div><button class="text-button" data-go="library">Ver todos <span>→</span></button></div><div class="game-grid compact-grid" id="playing-grid"></div>
    </section>
    <section class="page" id="page-library"><div class="page-heading"><div><p class="eyebrow">A TUA COLEÇÃO</p><h1>A minha biblioteca</h1><p class="subheading">Todos os teus mundos, num só lugar.</p></div><button class="button button-primary" data-add>＋ Adicionar jogo</button></div><div class="toolbar"><label class="search-field"><span>⌕</span><input id="library-search" type="search" placeholder="Procurar por título…"></label><select id="filter-platform" aria-label="Filtrar por plataforma"><option value="">Todas as plataformas</option></select><select id="filter-genre" aria-label="Filtrar por género"><option value="">Todos os géneros</option></select><select id="filter-status" aria-label="Filtrar por estado"><option value="">Todos os estados</option><option value="backlog">Por jogar</option><option value="playing">A jogar</option><option value="completed">Concluído</option><option value="paused">Em pausa</option><option value="abandoned">Abandonado</option></select><select id="sort-games" aria-label="Ordenar jogos"><option value="recent">Mais recentes</option><option value="title">Nome A–Z</option><option value="rating">Melhor avaliação</option><option value="hours">Mais horas</option></select><div class="view-toggle"><button class="view-button selected" data-view="grid" aria-label="Vista em grelha">▦</button><button class="view-button" data-view="list" aria-label="Vista em lista">☷</button></div></div><div class="result-line"><span id="result-count">0 jogos</span><button class="text-button clear-filters" id="clear-filters">Limpar filtros</button></div><div class="game-grid library-grid" id="library-grid"></div></section>
    <section class="page" id="page-wishlist"><div class="page-heading"><div><p class="eyebrow">O QUE VEM A SEGUIR</p><h1>Lista de desejos</h1><p class="subheading">As aventuras que estão à tua espera.</p></div><button class="button button-primary" data-add data-wishlist>＋ Adicionar à lista</button></div><div class="game-grid library-grid" id="wishlist-grid"></div></section>
    <section class="page" id="page-collections"><div class="page-heading"><div><p class="eyebrow">À TUA MANEIRA</p><h1>Coleções</h1><p class="subheading">Agrupa os jogos por histórias, géneros ou qualquer ideia tua.</p></div><button class="button button-primary" id="add-collection">＋ Nova coleção</button></div><div class="collection-grid" id="collection-grid"></div></section>
    <footer class="footer"><span>ARCADIA <i>·</i> A TUA BIBLIOTECA, AS TUAS REGRAS</span><span>Feito para as próximas aventuras.</span></footer>
  </main>
</div>
<div class="modal-backdrop" id="game-modal" aria-hidden="true"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header class="modal-header"><div><p class="eyebrow">A TUA COLEÇÃO</p><h2 id="modal-title">Adicionar jogo</h2></div><button class="close-button" data-close aria-label="Fechar">×</button></header><form id="game-form" enctype="multipart/form-data"><input type="hidden" name="id"><input type="hidden" name="csrf" value="<?= htmlspecialchars(csrf_token(), ENT_QUOTES) ?>"><div class="form-grid"><label class="field full"><span>Título <i>*</i></span><input name="title" required maxlength="160" placeholder="Ex.: The Legend of Zelda: Tears of the Kingdom"></label><label class="field"><span>Plataforma</span><input name="platform" maxlength="80" placeholder="Ex.: Nintendo Switch"></label><label class="field"><span>Género</span><input name="genre" maxlength="80" placeholder="Ex.: Aventura"></label><label class="field"><span>Estado</span><select name="status"><option value="backlog">Por jogar</option><option value="playing">A jogar</option><option value="completed">Concluído</option><option value="paused">Em pausa</option><option value="abandoned">Abandonado</option></select></label><label class="field"><span>Horas jogadas</span><input name="hours" type="number" min="0" step="0.5" placeholder="0"></label><label class="field"><span>Avaliação pessoal (0–10)</span><input name="rating" type="number" min="0" max="10" step="0.5" placeholder="—"></label><label class="field"><span>Data de lançamento</span><input name="release_date" type="date"></label><label class="field full"><span>Descrição</span><textarea name="description" rows="3" maxlength="2000" placeholder="O que torna este jogo especial?"></textarea></label><label class="field full"><span>Notas privadas</span><textarea name="notes" rows="2" maxlength="3000" placeholder="As tuas notas, objetivos ou memórias…"></textarea></label><label class="field full"><span>Capa do jogo</span><div class="upload-control"><input name="cover" type="file" accept="image/jpeg,image/png,image/webp,image/gif"><small>JPG, PNG, WebP ou GIF. Até 5 MB.</small></div></label><label class="check-field"><input name="favorite" type="checkbox" value="1"><span>♡</span> Marcar como favorito</label><label class="check-field"><input name="is_wishlist" type="checkbox" value="1"><span>＋</span> Guardar na lista de desejos</label></div><div class="form-error" id="form-error" role="alert"></div><footer class="modal-footer"><button type="button" class="button button-outline" data-close>Cancelar</button><button type="submit" class="button button-primary" id="save-game">Guardar jogo</button></footer></form></section></div>
<div class="toast" id="toast" role="status" aria-live="polite"></div>
</body></html>
